### ISSUE TITLE
How to configure it for AWS Load Balancer.

### ISSUE THREAD

**Issue by sinanopcommerce** [JonPSmith/Net.DistributedFileStoreCache#2]
Can you please guide me a little that, how to configure it for AWS Load Balancer? Because the JSON file needs to keep a central place so it can be accessed by each instance.

**Comment by JonPSmith** [comment]
Have a look at the [Registering FileStore Cache](https://github.com/JonPSmith/Net.DistributedFileStoreCache/wiki/Registering-FileStore-Cache) documentation.

As you said "JSON file needs to keep a central place so it can be accessed by each instance". Have a look at [this section](https://github.com/JonPSmith/Net.DistributedFileStoreCache/wiki/Registering-FileStore-Cache) from the "Registering FileStore Cache" document.
