### ISSUE TITLE
Using with Kubernetes Persistent Volume

### ISSUE THREAD

**Issue by kimbirkelund** [JonPSmith/Net.DistributedFileStoreCache#4]
First of, nice lib 👍

I trying to use this with Kubernetes using a Persistent Volume for storage. The basics are working - the cache file is updated. However updates does not seem to get propagated to the other instances. I'm guessing it is `FileSystemWatcher` that does work.

Do you have experience using the lib in Kubernetes?

**Comment by JonPSmith** [comment]
Hi @kimbirkelund,

I don't use Kubernetes so I can't really help, but I doubt that Kubernetes supports the `FileSystemWatcher` event. 

Sorry I can't help.

**Comment by kimbirkelund** [comment]
You're right - it does not support events. I got around this by using reflection to mark the local cache as invalid (I could live with the degraded performance for now).

However it turns out locking also does not work as it needs to so the JSON file gets corrupted when there are concurrent writes.

Oh well, Redis it is :)
